wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("create", views.create, name="create"),
    path("random", views.random, name="random"),
    path("search", views.search, name="search"),
    path("wiki/<str:entry>/edit", views.edit, name="edit"),
    path("wiki/<str:entry>", views.entry, name="entry")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django import forms

from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse
import markdown2
import secrets

from . import util

class NewEntryForm(forms.Form):
    entry_title = forms.CharField(label="New Title", widget=forms.TextInput(attrs={'class' : 'form-control col-md-8 col-lg-8'}))
    entry = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control col-lg-10'}), label="Entry:")
    edit = forms.BooleanField(initial=False, widget=forms.HiddenInput(), required=False)

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def create(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            entry = form.cleaned_data["entry"]
            entry_title = form.cleaned_data["entry_title"]
            if(util.get_entry(entry_title) is None or form.cleaned_data["edit"] is True):
                util.save_entry(entry_title,entry)
                return HttpResponseRedirect(reverse("wiki:entry", kwargs={'entry': entry_title}))
            else:
                return render(request, "encyclopedia/pagealreadyExist.html", {
            "entry_title": entry})
        else:
            return render(request, "encyclopedia/create.html", {
                "form": form
            })


    return render(request, "encyclopedia/create.html", {
        "form" : NewEntryForm()
    })

def entry(request, entry): 
    md = markdown2.Markdown()
    entryPage = util.get_entry(entry)
    if entryPage is None:
        return render(request, "encyclopedia/pagedonotExist.html", {
            "entry_title": entry})
         
    else:
        return render(request, "encyclopedia/entry.html", {
            "entry": md.convert(entryPage),
            "entry_title": entry
        })

def random(request):
    entries = util.list_entries()
    rndmEntry1 = secrets.choice(entries)
    return HttpResponseRedirect(reverse("wiki:entry", kwargs={'entry': rndmEntry1}))

def search(request):
    query = request.GET.get('q','')
    if(util.get_entry(query) is not None):
        return HttpResponseRedirect(reverse("wiki:entry", kwargs={'entry': query}))

    else:
        upperEntries = []
        for entry in util.list_entries():
            if query.upper() in entry.upper():
                upperEntries.append(entry)

        return render(request, "encyclopedia/index.html", {
        "entries": upperEntries,
        "search": True,
        "query": query
    })
  
def edit(request, entry):
    entryPage = util.get_entry(entry)
    if entryPage is None:
        return render(request, "encyclopedia/pagedonotExist.html", {
            "entry_title": entry
        })
    else:
        form = NewEntryForm()
        form.fields["entry_title"].initial = entry     
        form.fields["entry_title"].widget = forms.HiddenInput()
        form.fields["entry"].initial = entryPage
        form.fields["edit"].initial = True
        return render(request, "encyclopedia/create.html", {
            "form": form,
            "edit": form.fields["edit"].initial,
            "entry_title": form.fields["entry_title"].initial
        })        
              


    

wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - Create an entry
{% endblock %}

{% block body %}
    

    {% if edit %}
    <div class="alert col-lg-11" role="alert" style="background-color:darkgrey;">
        <h1>Editing {{ entry_title }}</h1>
    </div>
       
    {% else %}

    <div class="alert col-lg-11" role="alert" style="padding: 0%;text-align: center;background-color: darkgray;">
        <h1>Create Entry</h1>
    </div>
        
    {% endif %}
    <br>

    <form action="{% url 'wiki:create' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="" class="btn btn-outline-primary">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit {{ entry_title }}
{% endblock %}

{% block body %}
<h1 class="alert alert-dark col-lg-11">{{ entry_title|safe }}</h1>
{{ entry|safe }}
<div>
    <a href="/wiki/{{ entry_title }}/edit"><button type="button" class="btn btn-outline-primary">Edit: <a href="/wiki/{{ entry_title }}/edit"></a></button></a>
</div>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

{% if search %}
        <h2>Searching for {{ query }}</h2>
        
    {% else %}
        <h1 class="alert col-lg-11" style="background-color:rgb(163, 112, 112);text-align: center;">All Pages</h1></br>        
    {% endif %}

    
        {% for entry in entries %}
            <a href="/wiki/{{ entry }}" class="list-group-item list-group-item-action list-group-item-warning col-lg-9" style="text-align: center;margin-left: 8%;margin-right: 8%;margin-bottom:2px;">{{ entry }}</a>
        {% endfor %}
    

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body style="background-color: rgb(235, 235, 235);">
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <div class="badge badge-pill badge-dark" style="text-align: center;width: 100%;margin: 5%;padding: 2%;" >
                    <h1 >Wiki</h1>
                </div>
                <div style="margin:5%;width: 100%;">
                    <form action="search">
                        <input class="form-control" type="text" name="q" placeholder="Search Encyclopedia" style="text-align: center;">
                    </form>
                </div>
                <div>
                    <a href="{% url 'wiki:index' %}" class="badge badge-pill badge-light" style="width: 100%;font-size: 25px;margin: 5%;padding: 2%;">Home</a>
                </div>
                <div >
                    <a href="{% url 'wiki:create' %}" class="badge badge-pill badge-light" style="width: 100%;font-size: 25px;margin: 5%;">Create New<br>Page</a>
                </div>
                <div >
                    <a href="{% url 'wiki:random' %}" class="badge badge-pill badge-light" style="width: 100%;font-size: 25px;margin: 5%;">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/pagealreadyExist.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<div class="alert alert-dark" role="alert">
    <h1>This page already exist. Go to the <a href="{% url 'wiki:create' %}" class="alert-link">Create Entry Page</a> and try a different title.</h1>
  </div>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/pagedonotExist.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<div class="alert alert-dark" role="alert">
    <h1>This page doesn't exist. Go to the <a href="{% url 'wiki:index' %}" class="alert-link">Home Page</a></h1>
  </div>
{% endblock %}